const fonts = {
	".HeaderH1---Bold": {
		fontFamily: "Roboto",
		fontSize: "60px",
		fontWeight: "bold",
		fontStretch: "normal",
		fontStyle: "normal",
		lineHeight: 1.4,
		letterSpacing: "normal",
	},
	".HeaderH1---Medium": {
		fontFamily: "Roboto",
		fontSize: "60px",
		fontWeight: 500,
		fontStretch: "normal",
		fontStyle: "normal",
		lineHeight: 1.4,
		letterSpacing: "normal",
	},
	".HeaderH2---Bold": {
		fontFamily: "Roboto",
		fontSize: "52px",
		fontWeight: "bold",
		fontStretch: "normal",
		fontStyle: "normal",
		lineHeight: 1.5,
		letterSpacing: "normal",
	},
	".HeaderH2---Medium": {
		fontFamily: "Roboto",
		fontSize: "52px",
		fontWeight: 500,
		fontStretch: "normal",
		fontStyle: "normal",
		lineHeight: 1.5,
		letterSpacing: "normal",
	},
	".HeaderH3---Bold": {
		fontFamily: "Roboto",
		fontSize: "40px",
		fontWeight: "bold",
		fontStretch: "normal",
		fontStyle: "normal",
		lineHeight: 1.4,
		letterSpacing: "normal",
	},
	".HeaderH3---Medium": {
		fontFamily: "Roboto",
		fontSize: "40px",
		fontWeight: 500,
		fontStretch: "normal",
		fontStyle: "normal",
		lineHeight: 1.4,
		letterSpacing: "normal",
	},
	".HeaderH4---Bold": {
		fontFamily: "Roboto",
		fontSize: "32px",
		fontWeight: "bold",
		fontStretch: "normal",
		fontStyle: "normal",
		lineHeight: 1.5,
		letterSpacing: "normal",
	},
	".HeaderH4---Medium": {
		fontFamily: "Roboto",
		fontSize: "32px",
		fontWeight: 500,
		fontStretch: "normal",
		fontStyle: "normal",
		lineHeight: 1.5,
		letterSpacing: "normal",
	},
	".TitleT1---Bold": {
		fontFamily: "Roboto",
		fontSize: "24px",
		fontWeight: "bold",
		fontStretch: "normal",
		fontStyle: "normal",
		lineHeight: 1.5,
		letterSpacing: "normal",
	},
	".TitleT1---Medium": {
		fontFamily: "Roboto",
		fontSize: "24px",
		fontWeight: 500,
		fontStretch: "normal",
		fontStyle: "normal",
		lineHeight: 1.5,
		letterSpacing: "normal",
	},
	".TitleT1---Regular": {
		fontFamily: "Roboto",
		fontSize: "24px",
		fontWeight: "normal",
		fontStretch: "normal",
		fontStyle: "normal",
		lineHeight: 1.5,
		letterSpacing: "normal",
	},
	".TitleT2---Bold": {
		fontFamily: "Roboto",
		fontSize: "20px",
		fontWeight: "bold",
		fontStretch: "normal",
		fontStyle: "normal",
		lineHeight: 1.3,
		letterSpacing: "normal",
	},
	".TitleT2---Medium": {
		fontFamily: "Roboto",
		fontSize: "20px",
		fontWeight: 500,
		fontStretch: "normal",
		fontStyle: "normal",
		lineHeight: 1.3,
		letterSpacing: "normal",
	},
	".TitleT2---Regular": {
		fontFamily: "Roboto",
		fontSize: "20px",
		fontWeight: "normal",
		fontStretch: "normal",
		fontStyle: "normal",
		lineHeight: 1.3,
		letterSpacing: "normal",
	},
	".Body-TextB1---Bold": {
		fontFamily: "Roboto",
		fontSize: "16px",
		fontWeight: "bold",
		fontStretch: "normal",
		fontStyle: "normal",
		lineHeight: 1.5,
		letterSpacing: "normal",
	},
	".Body-TextB1---Medium": {
		fontFamily: "Roboto",
		fontSize: "16px",
		fontWeight: 500,
		fontStretch: "normal",
		fontStyle: "normal",
		lineHeight: 1.5,
		letterSpacing: "normal",
	},
	".Body-TextB1---Regular": {
		fontFamily: "Roboto",
		fontSize: "16px",
		fontWeight: "normal",
		fontStretch: "normal",
		fontStyle: "normal",
		lineHeight: 1.5,
		letterSpacing: "normal",
	},
	".Body-TextB2---SemiBold": {
		fontFamily: "Roboto",
		fontSize: "14px",
		fontWeight: 600,
		fontStretch: "normal",
		fontStyle: "normal",
		lineHeight: 1.4,
		letterSpacing: "normal",
	},
	".Body-TextB2---Medium": {
		fontFamily: "Roboto",
		fontSize: "14px",
		fontWeight: 500,
		fontStretch: "normal",
		fontStyle: "normal",
		lineHeight: 1.4,
		letterSpacing: "normal",
	},
	".Body-TextB2---Regular": {
		fontFamily: "Roboto",
		fontSize: "14px",
		fontWeight: "normal",
		fontStretch: "normal",
		fontStyle: "normal",
		lineHeight: 1.4,
		letterSpacing: "normal",
	},
	".CaptionC1---SemiBold": {
		fontFamily: "Roboto",
		fontSize: "12px",
		fontWeight: 600,
		fontStretch: "normal",
		fontStyle: "normal",
		lineHeight: 1.3,
		letterSpacing: "normal",
	},
	".CaptionC1---Medium": {
		fontFamily: "Roboto",
		fontSize: "12px",
		fontWeight: 500,
		fontStretch: "normal",
		fontStyle: "normal",
		lineHeight: 1.3,
		letterSpacing: "normal",
	},
	".CaptionC1---Regular": {
		fontFamily: "Roboto",
		fontSize: "12px",
		fontWeight: "normal",
		fontStretch: "normal",
		fontStyle: "normal",
		lineHeight: 1.3,
		letterSpacing: "normal",
	},
	".CaptionC2---SemiBold": {
		fontFamily: "Roboto",
		fontSize: "10px",
		fontWeight: 600,
		fontStretch: "normal",
		fontStyle: "normal",
		lineHeight: 1.4,
		letterSpacing: "normal",
	},
	".CaptionC2---Medium": {
		fontFamily: "Roboto",
		fontSize: "10px",
		fontWeight: 500,
		fontStretch: "normal",
		fontStyle: "normal",
		lineHeight: 1.4,
		letterSpacing: "normal",
	},
	".CaptionC2---Regular": {
		fontFamily: "Roboto",
		fontSize: "10px",
		fontWeight: "normal",
		fontStretch: "normal",
		fontStyle: "normal",
		lineHeight: 1.4,
		letterSpacing: "normal",
	},
};

module.exports = fonts;
